name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test and build
      run: |
        npm install
        npm test -- --forceExit
        npm run-script build
